csproj: remove trailing space from project names (#6)
There is an extra space following the paths of certain dll files. This
causes compilation failures when building on Linux:

    Restore complete (0.3s)
      OC2Modding net35 failed with 1 error(s) (0.1s)
        /Code/oc2-modding/OC2Modding/GameLog.cs(274,89): error CS0012: The type 'PointerInputModule' is defined in an assembly that is not referenced. You must add a reference to assembly 'UnityEngine.UI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

    Build failed with 1 error(s) in 0.6s

By removing the spaces, it becomes possible to build on Linux.

Signed-off-by: Sean Cross <sean@xobs.io>